module Instr : sig
	type op = 
		STOP | ADD | SUB | MUL | DIV | SDIV | MOD | SMOD | EXP | NOT | LT | GT | SLT | SGT
		| EQ | ISZERO | AND | OR | XOR | BYTE | ADDMOD | MULMOD | SIGNEXTEND | SHA3 | ADDRESS
		| BALANCE | ORIGIN | CALLER | CALLVALUE | CALLDATALOAD | CALLDATASIZE | CALLDATACOPY
		| CODESIZE | CODECOPY | GASPRICE | EXTCODESIZE | EXTCODECOPY | BLOCKHASH | COINBASE
		| TIMESTAMP | NUMBER | DIFFICULTY | GASLIMIT | POP | MLOAD | MSTORE | MSTORE8 | MSIZE
		| SLOAD | SSTORE | JUMP | JUMPI | PC | GAS | JUMPDEST
		| PUSH1 | PUSH2 | PUSH3 | PUSH4 | PUSH5 | PUSH6 | PUSH7 | PUSH8 | PUSH9 | PUSH10 | PUSH11
		| PUSH12 | PUSH13 | PUSH14 | PUSH15 | PUSH16 | PUSH17 | PUSH18 | PUSH19 | PUSH20 | PUSH21
		| PUSH22 | PUSH23 | PUSH24 | PUSH25 | PUSH26 | PUSH27 | PUSH28 | PUSH29 | PUSH30 | PUSH31 | PUSH32
		| DUP1 | DUP2 | DUP3 | DUP4 | DUP5 | DUP6 | DUP7 | DUP8 | DUP9 | DUP10  | DUP11 | DUP12 | DUP13
		| DUP14 | DUP15 | DUP16 
		| SWAP1 | SWAP2 | SWAP3 | SWAP4 | SWAP5 | SWAP6 | SWAP7 | SWAP8 | SWAP9 | SWAP10 | SWAP11
		| SWAP12 | SWAP13 | SWAP14 | SWAP15 | SWAP16 
		| LOG0 | LOG1 | LOG2 | LOG3 | LOG4
		| CREATE | CALL | CALLCODE | RETURN | DELEGATECALL | SUICIDE | INVALID

	type t = op * int list
	type contract = t list
	
	val of_bytes	: string -> t * string
	val to_hex 		: t -> string
	val to_asm 		: t -> string
	val dsize_of_op : op -> int
end
